---
title: "R Notebook"
output: html_notebook
---

Linear Regression Modelling for Soccer Data
-------------------------------------------

Load packages and set directories
```{r}
library(boot)
library(tidyverse)
library(broom)
setwd('~/Library/Mobile Documents/com~apple~CloudDocs/Udveksling/Studie/LS 88 - 3/Project/ls88_project-master')
```


Load data
```{r}
df = read_csv('dataframe.csv')
```


Retain only non-nominal features
```{r}
df <- df %>% 
      select(-X1, -id, -country_id, -league_id, -stage, -date, -match_api_id, -home_team_api_id,
            -away_team_api_id, -home_team_name, -away_team_name, -season)
```



Add Goal Difference as target variable and print distribution
```{r}
df <- df %>%
      mutate(goal_diff = home_team_goal - away_team_goal)

hist(df$goal_diff)
```
Looks perfectly normaly distributed.

As the target variable is derived from home_team_goal and away_team_goal we drop these variables.
```{r}
df <- df %>% 
      select(-home_team_goal, -away_team_goal)
```



Based on the correlation matrix from the Jupyter Notebook, we will drop variables:
home_points
away_points

As these 2 variables have too much correlation with the rest of the variables and are interdependent.
```{r}
df <- df %>% 
      select(-home_points, -away_points)
```


Fitting a linear model (iteration 1)
We have:
Response variable: Goal Difference
Explanatory variables: All Others + Intercept


-----------------
MODELLING ROUND 1
-----------------
```{r}
model1 <- lm(goal_diff ~ .,
              data = df)
#Print Summary
print(summary(model1))
```

Residuals look great. (centered around 0 with SD approximate to 1).


Notice how home_shotoff is significant with a negative effect on the goal difference (teams who miss a lot of shots at home will achieve a worse goal difference). It is also noticeable how getting a lot of corners on your home turf decreases your goal difference.
Surprisingly, shots on goal do not seem to have a significant effect.

---------------------
BOOTSTRAPPING ROUND 1
---------------------

Non-parametric bootstrapping for the coeffiecents with 5000 models.
We do not know the true distribution and use nonparametric bootstrap sampling with replacement accordingly.
This will use the empirical distribution.

```{r}
###Code copied from statmethods.net
#Function to obatin regression weights
bs <- function(formula, data, indices){
  d <- data[indices, ] #allows boot to select sample
  fit <- lm(formula, data = d)
  return(coef(fit))
}



#Bootstrapping with 5000 replications
results <- boot(df, 
                statistic = bs,
                R = 5000,
                formula = formula(model1) )

```

Plot distributions of parameters
```{r}
for(i in 1:length(results$t0)){
  hist(results$t[,i], 
       prob = TRUE,
       main = variable.names(model1)[i])
}
```

Coefficients with bootstrap histrograms centered around 0 shows lack of significance of the parameter.


Coefficients clearly centered around 0:
away_y1
home_shoton
away_shoton
away_corners


-----------------
MODELLING ROUND 2
-----------------
```{r}
model2 <- lm(goal_diff ~ . -away_y1 -home_shoton -away_shoton -away_corners,
              data = df)
#Print Summary
print(summary(model2))
```

---------------------
BOOTSTRAPPING ROUND 2
---------------------

```{r}
#Bootstrapping with 5000 replications
results <- boot(df, 
                statistic = bs,
                R = 5000,
                formula = formula(model2) )

```

Plot distributions of parameters
```{r}
for(i in 1:length(results$t0)){
  hist(results$t[,i], 
       prob = TRUE,
       main = variable.names(model2)[i])
}
```

Variables with close to 0 values:
away_fouls
away_poss
away_shotoff


-----------------
MODELLING ROUND 3
-----------------
```{r}
model3 <- lm(goal_diff ~ . -away_y1 -home_shoton -away_shoton -away_corners
             -away_fouls -away_poss -away_shotoff,
              data = df)
#Print Summary
print(summary(model3))
```

---------------------
BOOTSTRAPPING ROUND 3
---------------------

```{r}
#Bootstrapping with 5000 replications
results <- boot(df, 
                statistic = bs,
                R = 5000,
                formula = formula(model3) )

```

Plot distributions of parameters
```{r}
for(i in 1:length(results$t0)){
  hist(results$t[,i], 
       prob = TRUE,
       main = variable.names(model3)[i])
}
```

Removing home_fouls

-----------------
MODELLING ROUND 4
-----------------
```{r}
model4 <- lm(goal_diff ~ . -away_y1 -home_shoton -away_shoton -away_corners
             -away_fouls -away_poss -away_shotoff
             -home_fouls,
              data = df)
#Print Summary
print(summary(model4))
```

---------------------
BOOTSTRAPPING ROUND 4
---------------------

```{r}
#Bootstrapping with 5000 replications
results <- boot(df, 
                statistic = bs,
                R = 5000,
                formula = formula(model4) )

```

Plot distributions of parameters
```{r}
for(i in 1:length(results$t0)){
  hist(results$t[,i], 
       prob = TRUE,
       main = variable.names(model4)[i])
}
```

Model Selection has converged at model4


-----------------
SUMMARY
-----------------

The model is of the form
goal_difference = beta1*x1 + beta2*x2 ...,

where goal_difference = home_goal - away_goal

The final model became model 4 with coefficients
```{r}
summary(model4)
```

