---
title: "R Notebook"
output: html_notebook
---

Linear Modelling of Teams (Avg. Goals Conceded)
----------------------------
Initial assumption:
Teams which are only represented a few times are replaced by new teams with same "level" next season.


Load libraries
```{r}
library(boot)
library(tidyverse)
library(broom)
```

Load data
```{r}
df <- read.csv('grand_total_df.csv')
```



Show data
```{r}
head(df)
```

Divide into modelling and test data
```{r}
df_model <- df %>% 
            filter(season_home != '2015/2016')

df_test <- df %>% 
           filter(season_home == '2015/2016')
```


Pick out needed non-nominal variables
Points and goals are removed as they effectively consist of other variables in the data
```{r}
df_model <- df_model %>% 
      select(-X, -home_team_name, -season_home, -avg_total_goals, 
            -avg_goals_conceded_home, -avg_goals_conceded_away, -target_variable,
            -home_points, -away_points)
```


Fit linear model
```{r}
model1 <- lm(avg_total_goals_conceded ~ .,
             data = df_model)
```

Summarize the model
```{r}
summary(model1)
```


------
BOOTSTRAPPING (1)
------

```{r}
bs <- function(formula, data, indices){
  d <- data[indices, ] #allows boot to select sample
  fit <- lm(formula, data = d)
  return(coef(fit))
}

#Bootstrapping with 5000 replications
set.seed(200)
results <- boot(df_model, 
                statistic = bs,
                R = 5000,
                formula = formula(model1))
```


Plot distributions
```{r}

for(i in 1:length(results$t0)){
  hist(results$t[,i], 
       freq = TRUE,
       main = variable.names(model1)[i])
}
```

Coefficients where histograms from bootstrapping are centered around 0 show lack of significance.

Coefficients clearly centered around 0:
home_shotoff
home_fouls
home_r
away_team_goal
away_y2
away_poss
away_corners
away_r

---------------
MODELLING ROUND 2
---------------
We leave these variables out and model again
```{r}
model2 <- lm(avg_total_goals_conceded ~ . -home_shotoff -home_fouls -home_r -away_team_goal
                                          -away_team_goal -away_y2 -away_poss -away_corners -away_r,
             df_model)
```


--------------
BOOTSTRAPPING ROUND 2
--------------

```{r}
#Bootstrapping with 5000 replications
set.seed(200)
results <- boot(df_model, 
                statistic = bs,
                R = 5000,
                formula = formula(model2))
```


Plot distributions
```{r}
for(i in 1:length(results$t0)){
  hist(results$t[,i], 
       freq = TRUE,
       main = variable.names(model2)[i])
}
```

Coefficients with distributions close around 0:
home_shoton
home_corners
away_shoton
away_shotoff
away_fouls


-----------------
MODELLING ROUND 3
-----------------
Same as before. Drop these variables and model again
```{r}
model3 <- lm(avg_total_goals_conceded ~ . -home_shotoff -home_fouls -home_r -away_team_goal
                                          -away_team_goal -away_y2 -away_poss -away_corners -away_r
                                          -home_shoton -home_corners -away_shoton - away_shotoff -away_fouls,
             df_model)
```


---------------------
BOOTSTRAPPING ROUND 3
---------------------
```{r}
#Bootstrapping with 5000 replications
set.seed(200)
results <- boot(df_model, 
                statistic = bs,
                R = 5000,
                formula = formula(model3))
```


Plot distributions
```{r}
for(i in 1:length(results$t0)){
  hist(results$t[,i], 
       freq = TRUE,
       main = variable.names(model3)[i])
}
```

home_y2 and away_y1 are now near 0

-----------------
MODELLING ROUND 4
-----------------
```{r}
model4 <- lm(avg_total_goals_conceded ~ . -home_shotoff -home_fouls -home_r -away_team_goal
                                          -away_team_goal -away_y2 -away_poss -away_corners -away_r
                                          -home_shoton -home_corners -away_shoton - away_shotoff -away_fouls
                                          -home_y2 -away_y1,
             df_model)
```


---------------------
BOOTSTRAPPING ROUND 4
---------------------
```{r}
#Bootstrapping with 5000 replications
set.seed(200)
results <- boot(df_model, 
                statistic = bs,
                R = 5000,
                formula = formula(model4))
```


Plot distributions
```{r}
for(i in 1:length(results$t0)){
  hist(results$t[,i], 
       freq = TRUE,
       main = variable.names(model4)[i])
}
```


We conclude that all variables will be kept. 
Leaving us with the model
```{r}
summary(model4)
```
